controls:
  /azimuth-llm-chat/azimuth-llm/huggingface/model:
    type: TextControl
    required: true
  /azimuth-llm-chat/azimuth-llm/huggingface/token:
    type: TextControl
    secret: true
  # Use mirror to mimic yaml anchor in base Helm chart
  /azimuth-llm-chat/azimuth-llm/ui/appSettings/model_name:
    type: MirrorControl
    path: /azimuth-llm-chat/azimuth-llm/huggingface/model
    visuallyHidden: true
  # Azimuth UI doesn't handle json type ["integer","null"]
  # properly so we allow any type in JSON schema then
  # constrain to (optional) integer here.
  /azimuth-llm-chat/azimuth-llm/api/modelMaxContextLength:
    type: IntegerControl
    minimum: 100
    required: false

sortOrder:
  - /azimuth-llm-chat/azimuth-llm/huggingface/model
  - /azimuth-llm-chat/azimuth-llm/huggingface/token
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/model_instruction
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/page_title
  - /azimuth-llm-chat/azimuth-llm/api/image/version
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/temperature
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/max_tokens
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/frequency_penalty
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/presence_penalty
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/top_p
  - /azimuth-llm-chat/azimuth-llm/ui/appSettings/llm_params/top_k
  - /azimuth-llm-chat/azimuth-llm/api/modelMaxContextLength
